---
abstract: 'POSIX real-time timers'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  POSIX: 0
  Test::Exception: 0
  Test::More: 0.88
  Time::HiRes: 0
  threads: 0
configure_requires:
  Devel::CheckLib: 0
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POSIX-RT-Timer
requires:
  XSLoader: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=POSIX-RT-Timer
  repository: git://github.com/Leont/posix-rt-timer.git
version: 0.015
