---
name: POSIX-RT-Timer
version: 0.006
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: POSIX real-time timers
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
requires:
  perl: 5.008001
configure_requires:
  Module::Build: 0
provides:
  POSIX::RT::Clock:
    file: lib/POSIX/RT/Clock.pm
    version: 0.006
  POSIX::RT::Timer:
    file: lib/POSIX/RT/Timer.pm
    version: 0.006
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
