---
abstract: 'POSIX real-time timers'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  POSIX: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Time::HiRes: '0'
configure_requires:
  Devel::CheckLib: '0'
  Module::Build: '0.3601'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POSIX-RT-Timer
provides:
  POSIX::RT::Clock:
    file: lib/POSIX/RT/Clock.pm
    version: '0.017'
  POSIX::RT::Timer:
    file: lib/POSIX/RT/Timer.pm
    version: '0.017'
requires:
  XSLoader: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=POSIX-RT-Timer
  repository: git://github.com/Leont/posix-rt-timer.git
version: '0.017'
